"use client";

import { useMemo, useState } from "react";

type Role = "Student" | "Teacher" | "Administrator";
type View = "Dashboard" | "Learning" | "Assignments" | "Results" | "Calendar" | "Subscription" | "Payments" | "Analytics";

const icons: Record<string, string> = { Dashboard:"⌂", Learning:"▤", Assignments:"✓", Results:"◫", Calendar:"□", Subscription:"◆", Payments:"₵", Analytics:"↗" };
const roleNav: Record<Role, View[]> = {
  Student: ["Dashboard","Learning","Assignments","Results","Calendar","Subscription","Payments"],
  Teacher: ["Dashboard","Learning","Assignments","Results","Calendar","Analytics"],
  Administrator: ["Dashboard","Learning","Assignments","Results","Subscription","Payments","Analytics"],
};

const courses = [
  { title:"Computing", teacher:"Ms Adwoa Mensah", progress:72, lessons:24, color:"teal", icon:"</>", next:"Data & information", access:"Premium" },
  { title:"Mathematics", teacher:"Mr Daniel Owusu", progress:58, lessons:30, color:"blue", icon:"∑", next:"Algebraic expressions", access:"Free" },
  { title:"Integrated Science", teacher:"Ms Linda Asare", progress:41, lessons:26, color:"orange", icon:"⚗", next:"The human body", access:"Premium" },
  { title:"English Language", teacher:"Mrs Grace Abbey", progress:84, lessons:28, color:"green", icon:"Aa", next:"Creative writing", access:"Free" },
];

const assignments = [
  { title:"Create a simple algorithm", subject:"Computing", due:"Today, 6:00 PM", status:"In Progress", tone:"orange" },
  { title:"Algebra practice set", subject:"Mathematics", due:"Tue, 29 Jul", status:"Not Started", tone:"blue" },
  { title:"Digestive system model", subject:"Science", due:"Fri, 1 Aug", status:"Submitted", tone:"green" },
];

function ProgressRing({ value, small=false }: { value:number; small?:boolean }) {
  return <div className={`ring ${small?"small":""}`} style={{"--p":`${value*3.6}deg`} as React.CSSProperties}><span>{value}%</span></div>;
}

function Badge({ children, tone="teal" }: { children:React.ReactNode; tone?:string }) { return <span className={`badge ${tone}`}>{children}</span>; }

function Dashboard({ role, navigate }: { role:Role; navigate:(v:View)=>void }) {
  if (role === "Teacher") return <TeacherDashboard />;
  if (role === "Administrator") return <AdminDashboard />;
  return <>
    <section className="welcome">
      <div><Badge tone="mint">BASIC 7 • TERM 2</Badge><h1>Good afternoon, Ama <span>👋🏾</span></h1><p>Small steps every day become remarkable results. Keep going!</p><button onClick={()=>navigate("Learning")} className="primary">Continue learning <span>→</span></button></div>
      <div className="hero-art" aria-hidden="true"><div className="sun"/><div className="book">L</div><div className="spark s1">✦</div><div className="spark s2">✦</div></div>
    </section>
    <div className="stats-grid">
      <article className="stat"><div className="stat-icon teal-bg">◴</div><div><b>12 day</b><span>Learning streak</span></div><em>Best: 18 days</em></article>
      <article className="stat"><ProgressRing value={64} small/><div><b>64%</b><span>Overall progress</span></div><em>↑ 8% this month</em></article>
      <article className="stat"><div className="stat-icon orange-bg">✦</div><div><b>1,240</b><span>Learning points</span></div><em>Top 15% of class</em></article>
      <article className="stat"><div className="stat-icon blue-bg">✓</div><div><b>38</b><span>Activities done</span></div><em>4 this week</em></article>
    </div>
    <div className="section-head"><div><span className="eyebrow">MY SUBJECTS</span><h2>Pick up where you left off</h2></div><button className="text-button" onClick={()=>navigate("Learning")}>View all subjects →</button></div>
    <div className="course-grid">{courses.map((c)=><CourseCard key={c.title} course={c} onOpen={()=>navigate("Learning")}/>)}</div>
    <div className="dashboard-columns">
      <section className="panel"><div className="panel-title"><div><span className="eyebrow">UP NEXT</span><h2>Deadlines</h2></div><button className="icon-button">•••</button></div>{assignments.map(a=><div className="deadline" key={a.title}><div className={`date-dot ${a.tone}`}/><div><b>{a.title}</b><span>{a.subject} · {a.due}</span></div><Badge tone={a.tone}>{a.status}</Badge></div>)}</section>
      <section className="panel schedule"><div className="panel-title"><div><span className="eyebrow">THIS WEEK</span><h2>Learning schedule</h2></div><button className="text-button" onClick={()=>navigate("Calendar")}>Calendar →</button></div><div className="week">{["MON","TUE","WED","THU","FRI"].map((d,i)=><div className={i===0?"active":""} key={d}><span>{d}</span><b>{27+i}</b></div>)}</div><div className="event"><span className="event-time">3:30<br/><small>PM</small></span><div><Badge tone="blue">LIVE CLASS</Badge><b>Mathematics revision</b><span>with Mr Daniel Owusu · 45 min</span></div><button>Join</button></div></section>
    </div>
  </>;
}

function CourseCard({ course:c, onOpen }: { course:typeof courses[number]; onOpen:()=>void }) { return <article className="course-card" onClick={onOpen} tabIndex={0} role="button"><div className={`course-cover ${c.color}`}><span>{c.icon}</span><Badge tone={c.access==="Free"?"white":"dark"}>{c.access==="Premium"?"◆ ":""}{c.access}</Badge></div><div className="course-body"><span>{c.teacher}</span><h3>{c.title}</h3><div className="progress-label"><span>{c.progress}% complete</span><span>{c.lessons} lessons</span></div><div className="progress"><i style={{width:`${c.progress}%`}}/></div><p>Next: <b>{c.next}</b></p></div></article> }

function Learning() { const [lesson,setLesson]=useState(3); const locked=lesson>3; return <div className="learning-layout"><aside className="curriculum"><span className="eyebrow">COMPUTING • BASIC 7</span><h2>Digital citizenship</h2><div className="module-progress"><ProgressRing value={42} small/><div><b>Module progress</b><span>3 of 7 lessons</span></div></div><h4>MODULE 1 · ONLINE LIFE</h4>{["Your digital footprint","Staying safe online","Strong passwords","Responsible sharing","Knowledge check"].map((l,i)=><button key={l} className={lesson===i?"selected":""} onClick={()=>setLesson(i)}><span>{i<3?"✓":i===3?"▶":"◆"}</span><div><b>{l}</b><small>{i===4?"Premium quiz":`${6+i*2} min`}</small></div></button>)}</aside><section className="lesson"><div className="lesson-top"><div><Badge tone="mint">LESSON {lesson+1} OF 5</Badge><h1>{locked?"Responsible sharing":"Strong passwords, safer accounts"}</h1><p>Learn practical ways to protect your identity and make thoughtful choices online.</p></div><button className="icon-button">☆</button></div>{locked?<div className="premium-preview"><div className="lock">◆</div><Badge tone="orange">PREMIUM LESSON</Badge><h2>Keep your learning momentum going</h2><p>Preview the objectives, then unlock this lesson, practice activity and downloadable guide with Premium.</p><ul><li>Know what is safe to share</li><li>Recognise risky online requests</li><li>Use a decision checklist</li></ul><button className="primary">View Premium plans</button></div>:<><div className="video"><div className="play">▶</div><span>5:42</span></div><div className="lesson-tabs"><button className="active">Lesson</button><button>Notes</button><button>Resources <Badge>3</Badge></button><button>Discussion <Badge>8</Badge></button></div><article className="lesson-copy"><h2>What makes a password strong?</h2><p>A strong password is long, unique, and difficult for another person to guess. A passphrase can combine memorable words with numbers and symbols.</p><div className="objective"><b>By the end of this lesson, you can:</b><span>✓ explain why unique passwords matter</span><span>✓ create a secure passphrase</span><span>✓ identify two-factor authentication</span></div></article></>}<div className="lesson-actions"><button className="secondary" onClick={()=>setLesson(Math.max(0,lesson-1))}>← Previous</button><button className="complete">✓ Mark as complete</button><button className="primary" onClick={()=>setLesson(Math.min(4,lesson+1))}>Next lesson →</button></div></section></div> }

function Assignments() { return <section><div className="page-heading"><div><span className="eyebrow">MY WORK</span><h1>Assignments & projects</h1><p>Stay organised, submit your best work, and review teacher feedback.</p></div><button className="secondary">Filter assignments</button></div><div className="tabs"><button className="active">All work <Badge>8</Badge></button><button>Due soon</button><button>Submitted</button><button>Graded</button></div><div className="assignment-list">{[...assignments,{title:"My community interview",subject:"Social Studies",due:"4 Aug",status:"Graded",tone:"teal"}].map((a,i)=><article key={a.title}><div className={`assignment-icon ${a.tone}`}>{i===2?"⚗":"▤"}</div><div className="assignment-info"><Badge tone={a.tone}>{a.subject}</Badge><h3>{a.title}</h3><p>Clear instructions, rubric, supporting resources and submission history are available.</p><span>Due {a.due}</span></div><div className="assignment-status"><Badge tone={a.tone}>{a.status}</Badge><button className="secondary">{a.status==="Submitted"?"View submission":a.status==="Graded"?"View feedback":"Open work"}</button></div></article>)}</div></section> }

function Results() { return <section><div className="page-heading"><div><span className="eyebrow">TERM 2 PERFORMANCE</span><h1>Results & feedback</h1><p>Your progress is more than a score—use feedback to choose your next step.</p></div><button className="secondary">Download report</button></div><div className="results-hero"><ProgressRing value={78}/><div><Badge tone="green">ON TRACK</Badge><h2>Strong progress this term</h2><p>Your average improved by 6 points. Computing and English are your strongest subjects.</p></div><div className="mini-stat"><span>Class average</span><b>71%</b></div><div className="mini-stat"><span>Assessments</span><b>12</b></div></div><div className="panel"><div className="result-row header"><span>Subject</span><span>Score</span><span>Class average</span><span>Progress</span><span>Feedback</span></div>{courses.map((c,i)=><div className="result-row" key={c.title}><b>{c.title}</b><strong>{[86,74,68,82][i]}%</strong><span>{[72,69,70,76][i]}%</span><span className="trend">↗ {i+2}%</span><button className="text-button">View feedback →</button></div>)}</div></section> }

function CalendarView() { return <section><div className="page-heading"><div><span className="eyebrow">JULY 2026</span><h1>Learning calendar</h1><p>Lessons, live classes, assessments and deadlines in one place.</p></div><button className="primary">+ Add study time</button></div><div className="calendar-card"><div className="calendar-toolbar"><button>←</button><h2>July 2026</h2><button>→</button><Badge>Month</Badge></div><div className="calendar-grid">{["MON","TUE","WED","THU","FRI","SAT","SUN"].map(d=><b key={d}>{d}</b>)}{Array.from({length:35},(_,i)=><div key={i} className={i===27?"today":""}><span>{i<3?28+i:i-2}</span>{i===7&&<i className="cal-event blue">Maths live class</i>}{i===10&&<i className="cal-event orange">Algorithm due</i>}{i===16&&<i className="cal-event green">Science quiz</i>}{i===27&&<i className="cal-event teal">Today</i>}</div>)}</div></div></section> }

function Subscription({ payments=false }: { payments?:boolean }) { const [plan,setPlan]=useState("Termly"); if(payments)return <PaymentHistory/>; return <section><div className="page-heading"><div><span className="eyebrow">LUMA PREMIUM</span><h1>More learning, more possibilities</h1><p>Unlock the complete curriculum while keeping all your progress in one place.</p></div><Badge tone="orange">CURRENT PLAN: FREE</Badge></div><div className="billing-toggle">{["Monthly","Termly","Annual"].map(p=><button className={plan===p?"active":""} onClick={()=>setPlan(p)} key={p}>{p}{p==="Annual"&&<small>Save 20%</small>}</button>)}</div><div className="plans"><article><Badge>FREE FOREVER</Badge><h2>Explore</h2><div className="price">GH₵0</div><p>Essential lessons to begin your journey.</p><ul><li>✓ Selected free lessons</li><li>✓ Basic quizzes</li><li>✓ Learning progress</li><li className="muted">– Premium resources</li></ul><button className="secondary">Current plan</button></article><article className="featured"><Badge tone="orange">MOST POPULAR</Badge><h2>Luma Premium</h2><div className="price">GH₵{plan==="Monthly"?"45":plan==="Termly"?"110":"360"}<small> / {plan.toLowerCase()}</small></div><p>Complete access for one learner and class level.</p><ul><li>✓ Every lesson and video</li><li>✓ Assessments and revision packs</li><li>✓ Downloadable resources</li><li>✓ Certificates and offline access</li></ul><button className="primary">Choose Premium →</button></article><article><Badge tone="blue">FAMILY</Badge><h2>Luma Family</h2><div className="price">GH₵180<small> / term</small></div><p>Premium learning for up to three children.</p><ul><li>✓ Everything in Premium</li><li>✓ Three learner profiles</li><li>✓ Guardian progress summary</li><li>✓ Priority support</li></ul><button className="secondary">Choose Family</button></article></div><div className="payment-note"><span>🔒</span><div><b>Payments are securely processed by an authorised gateway</b><p>Mobile Money, cards and bank options where available. Luma never asks for or stores your PIN, full card number or CVV.</p></div></div></section> }

function PaymentHistory(){return <section><div className="page-heading"><div><span className="eyebrow">BILLING</span><h1>Payment history</h1><p>Track payments, subscription periods and receipts.</p></div><button className="primary">Upgrade to Premium</button></div><div className="stats-grid payment-stats"><article className="stat"><div><span>Current plan</span><b>Free</b></div></article><article className="stat"><div><span>Total paid</span><b>GH₵110.00</b></div></article><article className="stat"><div><span>Last payment</span><b>14 Jan 2026</b></div></article></div><div className="panel"><div className="result-row payment-row header"><span>Receipt</span><span>Plan</span><span>Date</span><span>Amount</span><span>Status</span><span></span></div><div className="result-row payment-row"><b>LUM-260114-0842</b><span>Premium · Termly</span><span>14 Jan 2026</span><strong>GH₵110.00</strong><Badge tone="green">Successful</Badge><button className="text-button">Receipt ↓</button></div><div className="result-row payment-row"><b>LUM-251002-0317</b><span>Premium · Termly</span><span>2 Oct 2025</span><strong>GH₵110.00</strong><Badge tone="orange">Refunded</Badge><button className="text-button">Receipt ↓</button></div></div></section>}

function TeacherDashboard(){return <><div className="page-heading"><div><Badge tone="mint">TEACHER WORKSPACE</Badge><h1>Welcome back, Ms Mensah</h1><p>Here’s what needs your attention across your classes today.</p></div><button className="primary">+ Create lesson</button></div><div className="stats-grid"><article className="stat"><div className="stat-icon teal-bg">♟</div><div><b>186</b><span>Active learners</span></div><em>Across 6 classes</em></article><article className="stat"><div className="stat-icon orange-bg">▤</div><div><b>14</b><span>To grade</span></div><em>5 due today</em></article><article className="stat"><div className="stat-icon blue-bg">↗</div><div><b>76%</b><span>Average score</span></div><em>↑ 4% this term</em></article><article className="stat"><div className="stat-icon green-bg">✓</div><div><b>8</b><span>Lesson notes</span></div><em>6 approved</em></article></div><div className="dashboard-columns"><section className="panel"><div className="panel-title"><div><span className="eyebrow">CLASS HEALTH</span><h2>Learners needing support</h2></div><button className="text-button">View all →</button></div>{["Kwame Boateng","Naana Quaye","Kofi Antwi"].map((n,i)=><div className="student-row" key={n}><span className="avatar">{n.split(" ").map(x=>x[0]).join("")}</span><div><b>{n}</b><span>Basic {7+i%2} · Computing</span></div><Badge tone={i===0?"orange":"blue"}>{i===0?"Behind schedule":"Low score"}</Badge><button className="icon-button">→</button></div>)}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">LESSON NOTES</span><h2>Weekly submissions</h2></div><button className="primary small-btn">Submit note</button></div>{["Week 8 · Basic 7 Computing","Week 8 · Basic 8 Computing","Week 7 · Basic 9 Computing"].map((n,i)=><div className="deadline" key={n}><div className={`date-dot ${i===0?"orange":"green"}`}/><div><b>{n}</b><span>Updated {i+1} day ago</span></div><Badge tone={i===0?"orange":"green"}>{i===0?"Returned":"Approved"}</Badge></div>)}</section></div></>}

function AdminDashboard(){return <><div className="page-heading"><div><Badge tone="mint">ADMINISTRATION</Badge><h1>Platform overview</h1><p>Monitor learning, people, content and revenue from one secure workspace.</p></div><button className="primary">+ Add user</button></div><div className="stats-grid"><article className="stat"><div className="stat-icon teal-bg">♟</div><div><b>3,842</b><span>Total learners</span></div><em>2,106 active today</em></article><article className="stat"><div className="stat-icon blue-bg">♟</div><div><b>20</b><span>Teachers</span></div><em>18 active</em></article><article className="stat"><div className="stat-icon orange-bg">◆</div><div><b>1,476</b><span>Premium learners</span></div><em>38.4% conversion</em></article><article className="stat"><div className="stat-icon green-bg">₵</div><div><b>GH₵48.6k</b><span>Revenue this month</span></div><em>↑ 12.3%</em></article></div><div className="dashboard-columns"><section className="panel chart-panel"><div className="panel-title"><div><span className="eyebrow">ENGAGEMENT</span><h2>Weekly active learners</h2></div><Badge>Last 8 weeks</Badge></div><div className="bars">{[42,58,48,70,65,82,76,92].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>W{i+1}</span></div>)}</div></section><section className="panel"><div className="panel-title"><div><span className="eyebrow">APPROVAL QUEUE</span><h2>Lesson notes to vet</h2></div><Badge tone="orange">7 PENDING</Badge></div>{["Basic 7 · Computing · Week 9","Basic 5 · Mathematics · Week 9","Basic 8 · Science · Week 8"].map((n,i)=><div className="deadline" key={n}><span className="avatar">{["AM","DO","LA"][i]}</span><div><b>{n}</b><span>Submitted {i+1}h ago</span></div><button className="secondary small-btn">Review</button></div>)}</section></div></>}

function Analytics(){return <section><div className="page-heading"><div><span className="eyebrow">INSIGHTS</span><h1>Analytics & reporting</h1><p>Filter learning and operational trends by class, subject, teacher and term.</p></div><button className="secondary">Export report ↓</button></div><div className="filterbar"><button>Term 2⌄</button><button>All class levels⌄</button><button>All subjects⌄</button><button>Last 30 days⌄</button></div><div className="stats-grid"><article className="stat"><div><span>Completion rate</span><b>74.8%</b></div><em>↑ 5.2%</em></article><article className="stat"><div><span>Average score</span><b>71.4%</b></div><em>↑ 2.8%</em></article><article className="stat"><div><span>Overdue work</span><b>326</b></div><em className="warn">Needs attention</em></article><article className="stat"><div><span>Active today</span><b>2,106</b></div><em>54.8% of learners</em></article></div><div className="panel chart-panel large"><div className="panel-title"><div><span className="eyebrow">LEARNING TREND</span><h2>Engagement and completion</h2></div><div><Badge>Engagement</Badge> <Badge tone="orange">Completion</Badge></div></div><div className="line-chart"><div className="gridline g1"/><div className="gridline g2"/><div className="gridline g3"/><div className="chart-line teal-line"/><div className="chart-line orange-line"/></div></div></section>}

export default function Home() {
  const [role,setRole]=useState<Role>("Student"); const [view,setView]=useState<View>("Dashboard"); const [sidebar,setSidebar]=useState(false);
  const title=useMemo(()=>view==="Learning"?"My Learning":view, [view]);
  const selectRole=(r:Role)=>{setRole(r);setView("Dashboard")};
  return <div className="app-shell"><aside className={`sidebar ${sidebar?"open":""}`}><div className="brand"><span>L</span><div><b>Luma</b><small>LEARNING</small></div><button onClick={()=>setSidebar(false)}>×</button></div><nav>{roleNav[role].map(v=><button key={v} className={view===v?"active":""} onClick={()=>{setView(v);setSidebar(false)}}><i>{icons[v]}</i><span>{v==="Learning"&&role!=="Student"?"Courses":v}</span>{v==="Assignments"&&<em>3</em>}</button>)}</nav><div className="upgrade-card"><span>✦</span><b>Unlock your potential</b><p>Get every lesson, quiz and resource.</p><button onClick={()=>setView("Subscription")}>Explore Premium</button></div><div className="sidebar-footer"><button><i>?</i><span>Help centre</span></button><button><i>⚙</i><span>Settings</span></button></div></aside><div className="main"><header><button className="menu" onClick={()=>setSidebar(true)}>☰</button><div className="crumb">Luma Learning <span>/</span> <b>{title}</b></div><div className="header-actions"><label className="role-switch">Preview as <select value={role} onChange={e=>selectRole(e.target.value as Role)}><option>Student</option><option>Teacher</option><option>Administrator</option></select></label><button className="notify">♧<em>3</em></button><div className="profile"><span>AN</span><div><b>Ama Nyarko</b><small>{role} · Basic 7</small></div><i>⌄</i></div></div></header><main>{view==="Dashboard"&&<Dashboard role={role} navigate={setView}/>} {view==="Learning"&&<Learning/>}{view==="Assignments"&&<Assignments/>}{view==="Results"&&<Results/>}{view==="Calendar"&&<CalendarView/>}{view==="Subscription"&&<Subscription/>}{view==="Payments"&&<Subscription payments/>}{view==="Analytics"&&<Analytics/>}</main></div></div>;
}
