"use client";

import { useState } from "react";

type Role = "Student" | "Teacher" | "Administrator";
type AuthMode = "login" | "signup" | null;

const studentNav = ["Dashboard","My Learning","My Courses","Live Classes","Assignments","Assessments","Practice Questions","Mock Examinations","Resources","Downloads","Discussion Forum","Certificates","Achievements","Messages","Calendar"];
const teacherNav = ["Dashboard","Classes","Lesson Notes","Learning Resources","Assignments","Assessments","Gradebook","Attendance","Student Performance","Discussion Forum","Calendar","Reports","Messages"];
const adminNav = ["Dashboard","Students","Teachers","User Management","Courses","Subjects & Classes","Learning Materials","Assessments","Timetable","Reports & Analytics","Payments","School Settings","Security & Audit"];

const continueCourses = [
  {title:"Python for Problem Solving",category:"COMPUTING",progress:72,time:"2h 15m left",tone:"violet",mark:"Py"},
  {title:"Core Mathematics",category:"MATHEMATICS",progress:58,time:"3h 40m left",tone:"sky",mark:"∑"},
  {title:"Integrated Science",category:"SCIENCE",progress:41,time:"4h 05m left",tone:"emerald",mark:"Sc"},
];

const recommended = [
  {title:"Artificial Intelligence Essentials",teacher:"Dr. Ama Mensah",rating:"4.9",students:"2.4k",level:"Beginner",duration:"8 weeks",tone:"violet",mark:"AI"},
  {title:"Flutter App Development",teacher:"Kwame Owusu",rating:"4.8",students:"1.8k",level:"Intermediate",duration:"10 weeks",tone:"sky",mark:"Fl"},
  {title:"Cybersecurity Foundations",teacher:"Nana Adjei",rating:"4.9",students:"3.1k",level:"Beginner",duration:"6 weeks",tone:"rose",mark:"Cy"},
  {title:"Data Analytics Masterclass",teacher:"Akosua Boateng",rating:"4.7",students:"1.2k",level:"Intermediate",duration:"9 weeks",tone:"amber",mark:"Da"},
];

function Logo(){return <div className="logo"><span>L</span><div><b>LUMA</b><small>LEARNING PLATFORM</small></div></div>}

function Landing({openAuth}:{openAuth:(role:Role,mode:Exclude<AuthMode,null>)=>void}){
  return <div className="landing">
    <nav className="landing-nav"><Logo/><div className="nav-links"><a href="#home">Home</a><a href="#courses">Courses</a><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#about">About</a></div><div className="nav-actions"><button className="ghost" onClick={()=>openAuth("Student","login")}>Log in</button><button className="button" onClick={()=>openAuth("Student","signup")}>Create account</button></div></nav>
    <main>
      <section className="hero" id="home"><div className="hero-copy"><span className="pill">Trusted by modern schools across Ghana</span><h1>Learn smarter.<br/><em>Achieve more.</em></h1><p>A complete digital learning platform that brings students, teachers, and schools together in one beautifully simple workspace.</p><div className="hero-actions"><button className="button large" onClick={()=>openAuth("Student","signup")}>Start learning free <span>→</span></button><a className="outline large" href="#courses">Explore courses</a></div><div className="proof"><div className="faces"><span>AN</span><span>KO</span><span>EA</span></div><p><b>12,000+ learners</b><br/>growing every day</p><div className="stars">★★★★★ <small>4.9/5</small></div></div></div>
      <div className="hero-product"><div className="orb orb-one"/><div className="orb orb-two"/><div className="product-window"><div className="window-bar"><i/><i/><i/><span>My learning dashboard</span></div><div className="mock-body"><aside><b>L</b>{[1,2,3,4,5].map(x=><i key={x}/>)}</aside><section><div className="mock-welcome"><div><small>WELCOME BACK</small><strong>Ready to learn, Ama?</strong><p>Keep your 12-day streak going.</p></div><div className="mini-ring">72%</div></div><div className="mock-stats"><i/><i/><i/></div><div className="mock-grid"><article><b>Continue learning</b><span/><span/><span/></article><article><b>Weekly progress</b><div className="mock-bars">{[35,58,45,76,64,90].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></article></div></section></div></div><div className="float-card fc-one"><span>✓</span><div><b>Lesson complete!</b><small>+120 learning points</small></div></div><div className="float-card fc-two"><span>🔥</span><div><b>12 day streak</b><small>Personal best: 18</small></div></div></div></section>
      <section className="trust"><span>Empowering learners at</span><div><b>ACCRA ACADEMY</b><b>WESLEY GIRLS'</b><b>PRESEC LEGON</b><b>ACHIMOTA SCHOOL</b><b>GIS</b></div></section>
      <section className="marketing" id="features"><span className="kicker">ONE PLATFORM. EVERY POSSIBILITY.</span><h2>Everything you need to<br/>move learning forward</h2><p>Purpose-built experiences for every member of your learning community.</p><div className="feature-grid"><article><span className="feature-icon violet">01</span><h3>Learn without limits</h3><p>Engaging lessons, assessments, live classes and resources that meet every learner where they are.</p><a onClick={()=>openAuth("Student","login")}>Student workspace →</a></article><article><span className="feature-icon sky">02</span><h3>Teach with confidence</h3><p>Create lessons, share resources, grade work and understand every learner’s progress in real time.</p><a onClick={()=>openAuth("Teacher","login")}>Teacher workspace →</a></article><article><span className="feature-icon emerald">03</span><h3>Lead with clarity</h3><p>Manage your entire school, monitor performance and make confident decisions from a single view.</p><a onClick={()=>openAuth("Administrator","login")}>Administrator workspace →</a></article></div></section>
      <section className="courses-section" id="courses"><div className="section-title"><div><span className="kicker">EXPLORE WHAT’S POSSIBLE</span><h2>Courses learners love</h2></div><button className="outline">Browse all courses →</button></div><div className="recommend-grid">{recommended.map(c=><CourseTile key={c.title} course={c}/>)}</div></section>
      <section className="cta" id="pricing"><span className="pill light">START YOUR JOURNEY TODAY</span><h2>Brighter learning starts here.</h2><p>Join a growing community of learners, educators, and schools building what comes next.</p><button className="button light-button" onClick={()=>openAuth("Student","signup")}>Create your free account →</button></section>
    </main>
    <footer><Logo/><p>Modern learning for ambitious students, inspiring teachers, and forward-thinking schools.</p><div><a>About</a><a>Help Center</a><a>Privacy</a><a>Terms</a><a>Contact</a></div><small>© 2026 LUMA Learning Platform. All rights reserved.</small></footer>
  </div>
}

function AuthDialog({role,mode,close,enter}:{role:Role;mode:Exclude<AuthMode,null>;close:()=>void;enter:(r:Role)=>void}){
  const [selected,setSelected]=useState(role);return <div className="modal-backdrop" onMouseDown={close}><div className="auth-card" role="dialog" aria-modal="true" aria-label={`${selected} ${mode}`} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><Logo/><div className="role-tabs">{(["Student","Teacher","Administrator"] as Role[]).map(r=><button key={r} className={r===selected?"active":""} onClick={()=>setSelected(r)}>{r}</button>)}</div><span className="kicker">{selected.toUpperCase()} PORTAL</span><h2>{mode==="signup"?"Create your account":"Welcome back"}</h2><p>{mode==="signup"?"Begin a more focused learning journey today.":"Sign in to continue to your LUMA workspace."}</p>{mode==="signup"&&<label>Full name<input placeholder="Enter your full name"/></label>}<label>Email address<input type="email" placeholder="name@example.com"/></label><label>Password<input type="password" placeholder="Enter your password"/></label><div className="auth-row"><label className="check"><input type="checkbox"/> Remember me</label><button>Forgot password?</button></div><button className="button auth-submit" onClick={()=>enter(selected)}>{mode==="signup"?"Create account":"Sign in securely"} →</button><small className="auth-note">Interface preview only. Connect an approved identity provider before accepting real credentials.</small></div></div>
}

function CourseTile({course}:{course:typeof recommended[number]}){return <article className="recommend-card"><div className={`course-thumb ${course.tone}`}><span>{course.mark}</span><button>•••</button></div><div className="recommend-body"><small>{course.teacher}</small><h3>{course.title}</h3><div className="rating"><b>★ {course.rating}</b><span>{course.students} learners</span></div><div className="course-meta"><span>{course.level}</span><span>{course.duration}</span></div><button className="outline">View course</button></div></article>}

function Dashboard({role,logout}:{role:Role;logout:()=>void}){
  const nav=role==="Student"?studentNav:role==="Teacher"?teacherNav:adminNav;const [active,setActive]=useState("Dashboard");const [dark,setDark]=useState(false);const [mobile,setMobile]=useState(false);
  return <div className={`dashboard-app ${dark?"dark":""}`}><aside className={mobile?"open":""}><Logo/><nav>{nav.map((n,i)=><button key={n} className={active===n?"active":""} onClick={()=>{setActive(n);setMobile(false)}}><i>{String(i+1).padStart(2,"0")}</i><span>{n}</span>{n==="Assignments"&&<em>3</em>}</button>)}</nav><div className="side-access"><b>Switch portal</b><button onClick={logout}>Student account</button><button onClick={logout}>Teacher login</button><button onClick={logout}>Administrator login</button></div><button className="logout" onClick={logout}>← Sign out</button></aside><div className="workspace"><header><button className="mobile-menu" onClick={()=>setMobile(!mobile)}>☰</button><label className="search"><span>⌕</span><input placeholder="Search courses, lessons, teachers, resources..."/></label><div className="top-actions"><button title="Messages">✉<em>2</em></button><button title="Notifications">♢<em>5</em></button><button className="theme" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><div className="user"><span>{role==="Student"?"AN":role==="Teacher"?"AM":"SA"}</span><div><b>{role==="Student"?"Ama Nyarko":role==="Teacher"?"Adwoa Mensah":"System Admin"}</b><small>{role}</small></div><i>⌄</i></div></div></header><main>{active==="Dashboard"?<RoleDashboard role={role}/>:<EmptyState title={active} role={role}/>}</main></div></div>
}

function RoleDashboard({role}:{role:Role}){if(role==="Teacher")return <TeacherHome/>;if(role==="Administrator")return <AdminHome/>;return <StudentHome/>}

function StudentHome(){return <><section className="dash-welcome"><div><span className="kicker">TUESDAY, 28 JULY</span><h1>Good morning, Ama <em>✦</em></h1><p>Continue your learning journey today. You’re making excellent progress.</p></div><div className="streak"><span>🔥</span><div><small>LEARNING STREAK</small><b>12 days</b><em>Personal best: 18 days</em></div></div></section><section className="quick-actions"><button><i>▶</i><span><b>Continue learning</b><small>Resume your latest lesson</small></span></button><button><i>⌁</i><span><b>Join live class</b><small>Mathematics · 3:30 PM</small></span></button><button><i>✓</i><span><b>Take a quiz</b><small>3 practice sets ready</small></span></button><button><i>↓</i><span><b>Resources</b><small>24 saved downloads</small></span></button></section><div className="section-title compact"><div><span className="kicker">PICK UP WHERE YOU LEFT OFF</span><h2>Continue learning</h2></div><button>View all →</button></div><div className="continue-grid">{continueCourses.map(c=><article key={c.title} className="continue-card"><div className={`continue-art ${c.tone}`}><span>{c.mark}</span><button>•••</button><small>{c.category}</small></div><div className="continue-copy"><h3>{c.title}</h3><p>Build practical skills through interactive lessons and guided activities.</p><div className="progress-row"><span><i style={{width:`${c.progress}%`}}/></span><b>{c.progress}%</b></div><div className="card-bottom"><small>{c.time}</small><button>Resume learning →</button></div></div></article>)}</div><Stats/><div className="dashboard-grid"><Assignments/><WeeklyProgress/></div><LiveClass/><div className="section-title compact"><div><span className="kicker">DISCOVER SOMETHING NEW</span><h2>Recommended for you</h2></div><button>Browse courses →</button></div><div className="recommend-grid dashboard-recommend">{recommended.map(c=><CourseTile key={c.title} course={c}/>)}</div><div className="dashboard-grid lower"><Achievements/><Activity/></div></>}

function Stats(){const s=[["06","Courses enrolled","+2 this term"],["18","Assignments done","3 pending"],["84%","Average grade","↑ 6% this term"],["42h","Study time","8h this week"],["03","Certificates","1 nearly earned"],["92%","Attendance","Excellent"]];return <div className="stat-grid">{s.map((x,i)=><article key={x[1]}><i className={`s${i}`}>{String(i+1).padStart(2,"0")}</i><div><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div></article>)}</div>}
function Assignments(){return <section className="dash-panel"><div className="panel-head"><div><span className="kicker">UP NEXT</span><h3>Upcoming assignments</h3></div><button>View all →</button></div>{[["Create a simple algorithm","Computing","Today · 6:00 PM","High"],["Algebra practice set","Mathematics","29 Jul · 4:00 PM","Medium"],["Digestive system model","Science","1 Aug · 11:59 PM","Submitted"]].map((a,i)=><div className="assignment" key={a[0]}><span className={`subject-dot d${i}`}/><div><b>{a[0]}</b><small>{a[1]} · {a[2]}</small></div><em className={a[3].toLowerCase()}>{a[3]}</em></div>)}</section>}
function WeeklyProgress(){return <section className="dash-panel"><div className="panel-head"><div><span className="kicker">YOUR MOMENTUM</span><h3>Weekly study hours</h3></div><button>This week ⌄</button></div><div className="chart"><div className="chart-y"><span>8h</span><span>6h</span><span>4h</span><span>2h</span><span>0</span></div><div className="chart-bars">{[35,62,48,84,70,92,55].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><small>{["M","T","W","T","F","S","S"][i]}</small></div>)}</div></div></section>}
function LiveClass(){return <section className="live-class"><div className="live-mark"><span>LIVE</span><i>∑</i></div><div><small>NEXT LIVE CLASS</small><h3>Mathematics revision: Algebraic expressions</h3><p>With Mr Daniel Owusu · Today, 3:30 PM · 45 minutes</p></div><div className="countdown"><span><b>01</b><small>HRS</small></span><i>:</i><span><b>24</b><small>MIN</small></span></div><button>Join classroom →</button></section>}
function Achievements(){return <section className="dash-panel"><div className="panel-head"><div><span className="kicker">MILESTONES</span><h3>Recent achievements</h3></div><button>View all →</button></div><div className="badges">{[["⚡","Quick learner"],["★","Top performer"],["✓","Perfect attendance"],["⌘","Coding expert"]].map((b,i)=><div key={b[1]}><span className={`badge3d b${i}`}>{b[0]}</span><b>{b[1]}</b><small>Earned this term</small></div>)}</div></section>}
function Activity(){return <section className="dash-panel"><div className="panel-head"><div><span className="kicker">LATEST UPDATES</span><h3>Recent activity</h3></div><button>See history →</button></div><div className="timeline">{[["Completed ‘Strong passwords’","12 learning points · 20 min ago"],["Submitted Algebra practice","Mathematics · Yesterday"],["Earned Quick Learner badge","Computing · 2 days ago"],["Joined Science live class","45 minutes · 3 days ago"]].map((a,i)=><div key={a[0]}><i>{i+1}</i><span><b>{a[0]}</b><small>{a[1]}</small></span></div>)}</div></section>}
function TeacherHome(){return <><section className="role-hero"><div><span className="kicker">TEACHER WORKSPACE</span><h1>Make every learning moment count.</h1><p>Your classes are active and 14 submissions are ready for review.</p></div><button>+ Create learning activity</button></section><div className="stat-grid"><Metric value="186" label="Active learners" note="Across 6 classes"/><Metric value="14" label="To grade" note="5 due today"/><Metric value="76%" label="Class average" note="↑ 4% this term"/><Metric value="92%" label="Attendance" note="Excellent"/></div><div className="dashboard-grid"><Assignments/><section className="dash-panel"><div className="panel-head"><div><span className="kicker">CLASS HEALTH</span><h3>Learners needing support</h3></div><button>View class →</button></div>{["Kwame Boateng","Naana Quaye","Kofi Antwi"].map((n,i)=><div className="person-row" key={n}><span>{n.split(" ").map(x=>x[0]).join("")}</span><div><b>{n}</b><small>Basic {7+i%2} · Computing</small></div><em>{i?"Low score":"Behind schedule"}</em></div>)}</section></div><div className="upload-zone"><i>↑</i><div><h3>Share a learning resource</h3><p>Upload PDF, video, slides, documents, images, or audio lessons.</p></div><button>Choose files</button></div></>}
function AdminHome(){return <><section className="role-hero admin"><div><span className="kicker">ADMINISTRATION CONTROL CENTER</span><h1>Clarity for your entire institution.</h1><p>Monitor people, learning, operations, and revenue from one secure workspace.</p></div><button>+ Add user</button></section><div className="stat-grid"><Metric value="3,842" label="Total learners" note="2,106 active today"/><Metric value="20" label="Teachers" note="18 active"/><Metric value="74.8%" label="Completion rate" note="↑ 5.2%"/><Metric value="GH₵48.6k" label="Monthly revenue" note="↑ 12.3%"/></div><div className="dashboard-grid"><WeeklyProgress/><section className="dash-panel"><div className="panel-head"><div><span className="kicker">APPROVAL QUEUE</span><h3>Resources awaiting review</h3></div><button>Review all →</button></div>{["Basic 7 Computing · Week 9","Basic 5 Mathematics · Week 9","Basic 8 Science · Week 8"].map((x,i)=><div className="person-row" key={x}><span>{["AM","DO","LA"][i]}</span><div><b>{x}</b><small>Submitted {i+1} hour ago</small></div><em>Review</em></div>)}</section></div><section className="management-grid">{["User management","Academic management","Resource library","Payments & plans","Reports & analytics","Security & audit"].map((x,i)=><button key={x}><i>{String(i+1).padStart(2,"0")}</i><span><b>{x}</b><small>Open management workspace</small></span><em>→</em></button>)}</section></>}
function Metric({value,label,note}:{value:string;label:string;note:string}){return <article><i>•</i><div><b>{value}</b><span>{label}</span><small>{note}</small></div></article>}
function EmptyState({title,role}:{title:string;role:Role}){return <section className="empty-state"><span>{title.slice(0,2).toUpperCase()}</span><small>{role.toUpperCase()} WORKSPACE</small><h1>{title}</h1><p>This workspace is ready for the next product phase. The navigation, responsive shell, permissions context, and visual system are already in place.</p><button>Explore dashboard →</button></section>}

export default function Home(){const [auth,setAuth]=useState<{role:Role;mode:Exclude<AuthMode,null>}|null>(null);const [role,setRole]=useState<Role|null>(null);return <>{role?<Dashboard role={role} logout={()=>setRole(null)}/>:<Landing openAuth={(r,m)=>setAuth({role:r,mode:m})}/>} {auth&&<AuthDialog role={auth.role} mode={auth.mode} close={()=>setAuth(null)} enter={r=>{setRole(r);setAuth(null)}}/>}</>}
