import { randomBytes } from "node:crypto";
import { NextResponse } from "next/server";
import { requireRole,supabaseFetch } from "@/lib/supabase";
const temporaryPassword=()=>`Lu!${randomBytes(8).toString("base64url")}9`;
const allowedStatuses=["pending_verification","active","suspended","disabled","password_change_required"];

export async function GET(request:Request){const session=await requireRole(["administrator"]);if(!session)return NextResponse.json({error:"Forbidden"},{status:403});const query=new URL(request.url).searchParams;const role=query.get("role");const status=query.get("status");const search=query.get("search");const page=Math.max(1,Number(query.get("page")||1));const limit=25;let path=`/rest/v1/profiles?select=*,teacher_assignments(subjects,classes)&order=created_at.desc&limit=${limit}&offset=${(page-1)*limit}`;if(role)path+=`&role=eq.${encodeURIComponent(role)}`;if(status)path+=`&status=eq.${encodeURIComponent(status)}`;if(search)path+=`&or=(full_name.ilike.*${encodeURIComponent(search)}*,email.ilike.*${encodeURIComponent(search)}*,username.ilike.*${encodeURIComponent(search)}*)`;const result=await supabaseFetch(path,{headers:{Prefer:"count=exact"}},session.token);const total=Number(result.headers.get("content-range")?.split("/")[1]||0);return NextResponse.json({users:await result.json(),page,total,pages:Math.max(1,Math.ceil(total/limit))},{status:result.status})}

export async function POST(request:Request){const session=await requireRole(["administrator"]);if(!session)return NextResponse.json({error:"Forbidden"},{status:403});try{const body=await request.json();const {fullName,email,phone,staffId,username,subjects,classes,status="password_change_required"}=body;if(!fullName||!email||!phone||!staffId||!username||!Array.isArray(subjects)||!subjects.length||!Array.isArray(classes)||!classes.length)return NextResponse.json({error:"Complete every required teacher field, subject, and class assignment."},{status:400});if(!allowedStatuses.includes(status))return NextResponse.json({error:"Invalid account status."},{status:400});const password=temporaryPassword();const created=await supabaseFetch("/auth/v1/admin/users",{method:"POST",body:JSON.stringify({email:String(email).trim().toLowerCase(),password,email_confirm:true,user_metadata:{full_name:String(fullName).trim(),phone:String(phone).trim(),staff_id:String(staffId).trim(),username:String(username).trim().toLowerCase()},app_metadata:{role:"teacher"}})},undefined,true);const user=await created.json();if(!created.ok)return NextResponse.json({error:user.msg||"Email, username, or staff ID already exists."},{status:409});await supabaseFetch(`/rest/v1/profiles?id=eq.${user.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({full_name:fullName,email:String(email).trim().toLowerCase(),phone,staff_id:staffId,username:String(username).trim().toLowerCase(),role:"teacher",status,created_by:session.user.id})},undefined,true);await supabaseFetch("/rest/v1/teacher_assignments",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify([{teacher_id:user.id,subjects,classes,assigned_by:session.user.id}])},undefined,true);await Promise.all([supabaseFetch("/rest/v1/audit_logs",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({actor_id:session.user.id,action:"teacher_account_created",affected_record:user.id,new_value:{email,staffId,username,subjects,classes,status}})},undefined,true),supabaseFetch("/rest/v1/notifications",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,title:"Teacher account created",body:"Your LUMA teacher account is ready. Sign in with the credentials issued by the administrator."})},undefined,true)]);return NextResponse.json({id:user.id,temporaryPassword:password,requiresPasswordChange:status==="password_change_required"},{status:201})}catch{return NextResponse.json({error:"Unable to create the teacher account."},{status:500})}}
